#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ReadApp.Resource", IsApplication=true)]

namespace ReadApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050014
			public const int BlocoPaginas = 2131034132;
			
			// aapt resource value: 0x7f050012
			public const int BlocolivroInformacao = 2131034130;
			
			// aapt resource value: 0x7f050022
			public const int CapitulosButton = 2131034146;
			
			// aapt resource value: 0x7f050001
			public const int atualizarNumeroPagina = 2131034113;
			
			// aapt resource value: 0x7f05001a
			public const int barraDeProgresso2 = 2131034138;
			
			// aapt resource value: 0x7f050017
			public const int barraDeSeparacao = 2131034135;
			
			// aapt resource value: 0x7f050011
			public const int blocoInfomacao = 2131034129;
			
			// aapt resource value: 0x7f050003
			public const int capitulos_listView = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int editarAnoLivro = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int editarAutorLivro = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int editarNomeLivro = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int editarQuantidadePaginasLivro = 2131034119;
			
			// aapt resource value: 0x7f050028
			public const int fragmentContainer = 2131034152;
			
			// aapt resource value: 0x7f05000a
			public const int iniciarLeituraAno = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int iniciarLeituraAutor = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int iniciarLeituraNomeLivro = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int iniciarLeituraQuantidadePaginas = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int inserirAnoLivro = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int inserirAutorLivro = 2131034125;
			
			// aapt resource value: 0x7f050029
			public const int inserirLivro = 2131034153;
			
			// aapt resource value: 0x7f05000c
			public const int inserirNomeLivro = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int inserirQuantidadePaginasLivro = 2131034127;
			
			// aapt resource value: 0x7f05001d
			public const int lendoAnoPublicacao = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int lendoAutor = 2131034140;
			
			// aapt resource value: 0x7f05001f
			public const int lendoBarraSeparacao = 2131034143;
			
			// aapt resource value: 0x7f050021
			public const int lendoInicioDaLeitura = 2131034145;
			
			// aapt resource value: 0x7f050010
			public const int lendoLayout2 = 2131034128;
			
			// aapt resource value: 0x7f050023
			public const int lendoListViewTab = 2131034147;
			
			// aapt resource value: 0x7f05001b
			public const int lendoNomeLivro = 2131034139;
			
			// aapt resource value: 0x7f05001e
			public const int lendoPaginaAtual = 2131034142;
			
			// aapt resource value: 0x7f050020
			public const int lendoPagonaTotal = 2131034144;
			
			// aapt resource value: 0x7f050019
			public const int lendoReadUpdateImage = 2131034137;
			
			// aapt resource value: 0x7f050002
			public const int linearLayout1 = 2131034114;
			
			// aapt resource value: 0x7f050024
			public const int listView1 = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int livroAlterarInformacoes = 2131034149;
			
			// aapt resource value: 0x7f050027
			public const int livroRemover = 2131034151;
			
			// aapt resource value: 0x7f050026
			public const int livroVerCapitulos = 2131034150;
			
			// aapt resource value: 0x7f050013
			public const int nomeLivro = 2131034131;
			
			// aapt resource value: 0x7f05002a
			public const int nomeQueroLerItem = 2131034154;
			
			// aapt resource value: 0x7f050016
			public const int numeroPaginaAtual = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int numeroPaginaTotal = 2131034136;
			
			// aapt resource value: 0x7f050015
			public const int paginaText = 2131034133;
			
			// aapt resource value: 0x7f05002b
			public const int quantidadePaginasQueroLerItem = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int tem_certeza = 2131034156;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int atualizar_leitura = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int capitulos_list = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int editar_livro = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int iniciar_leitura = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int inserir_livro = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int leitura_item2 = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int lendo_item = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int lendo_tab = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int list_tab = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int livro_opcoes = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Main = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int queroLer_item = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int sim_nao = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int lendo = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int lido = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int queroLer = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
