#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ReadApp.Resource", IsApplication=true)]

namespace ReadApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05003b
			public const int BlocoPaginas = 2131034171;
			
			// aapt resource value: 0x7f050039
			public const int BlocolivroInformacao = 2131034169;
			
			// aapt resource value: 0x7f050017
			public const int adicionarCapitulo = 2131034135;
			
			// aapt resource value: 0x7f050006
			public const int atualizarNumeroPagina = 2131034118;
			
			// aapt resource value: 0x7f050041
			public const int barraDeProgresso2 = 2131034177;
			
			// aapt resource value: 0x7f05003e
			public const int barraDeSeparacao = 2131034174;
			
			// aapt resource value: 0x7f050038
			public const int blocoInfomacao = 2131034168;
			
			// aapt resource value: 0x7f050014
			public const int capituloId = 2131034132;
			
			// aapt resource value: 0x7f05000d
			public const int capituloInfoComentario = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int capituloInfoEditar = 2131034126;
			
			// aapt resource value: 0x7f05000c
			public const int capituloInfoId = 2131034124;
			
			// aapt resource value: 0x7f050009
			public const int capituloInfoItemNomeCapitulo = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int capituloInfoNumero = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int capituloInfoPaginaFinal = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int capituloInfoPaginaInicial = 2131034122;
			
			// aapt resource value: 0x7f050010
			public const int capituloItemNomeCapitulo = 2131034128;
			
			// aapt resource value: 0x7f050015
			public const int capituloNomeLivro = 2131034133;
			
			// aapt resource value: 0x7f05000f
			public const int capituloNumero = 2131034127;
			
			// aapt resource value: 0x7f050013
			public const int capituloPaginaFinal = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int capituloPaginaInicial = 2131034130;
			
			// aapt resource value: 0x7f050016
			public const int capitulos_listView = 2131034134;
			
			// aapt resource value: 0x7f050023
			public const int editarAnoLivro = 2131034147;
			
			// aapt resource value: 0x7f050022
			public const int editarAutorLivro = 2131034146;
			
			// aapt resource value: 0x7f05001a
			public const int editarAventura = 2131034138;
			
			// aapt resource value: 0x7f050020
			public const int editarBiografia = 2131034144;
			
			// aapt resource value: 0x7f05001f
			public const int editarDidatico = 2131034143;
			
			// aapt resource value: 0x7f050019
			public const int editarEpico = 2131034137;
			
			// aapt resource value: 0x7f05001c
			public const int editarFantaisa = 2131034140;
			
			// aapt resource value: 0x7f05001e
			public const int editarFiccao = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int editarGuia = 2131034141;
			
			// aapt resource value: 0x7f050021
			public const int editarNomeLivro = 2131034145;
			
			// aapt resource value: 0x7f050024
			public const int editarQuantidadePaginasLivro = 2131034148;
			
			// aapt resource value: 0x7f050018
			public const int editarRomance = 2131034136;
			
			// aapt resource value: 0x7f05001b
			public const int editarTerror = 2131034139;
			
			// aapt resource value: 0x7f05005d
			public const int fragmentContainer = 2131034205;
			
			// aapt resource value: 0x7f050027
			public const int iniciarLeituraAno = 2131034151;
			
			// aapt resource value: 0x7f050026
			public const int iniciarLeituraAutor = 2131034150;
			
			// aapt resource value: 0x7f050025
			public const int iniciarLeituraNomeLivro = 2131034149;
			
			// aapt resource value: 0x7f050028
			public const int iniciarLeituraQuantidadePaginas = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int iniciarLeituraTags = 2131034153;
			
			// aapt resource value: 0x7f050035
			public const int inserirAnoLivro = 2131034165;
			
			// aapt resource value: 0x7f050034
			public const int inserirAutorLivro = 2131034164;
			
			// aapt resource value: 0x7f05002c
			public const int inserirAventura = 2131034156;
			
			// aapt resource value: 0x7f050032
			public const int inserirBiografia = 2131034162;
			
			// aapt resource value: 0x7f050004
			public const int inserirCapituloComentario = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int inserirCapituloNome = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int inserirCapituloNumber = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int inserirCapituloPaginaFinal = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int inserirCapituloPaginaInicial = 2131034114;
			
			// aapt resource value: 0x7f050031
			public const int inserirDidatico = 2131034161;
			
			// aapt resource value: 0x7f05002b
			public const int inserirEpico = 2131034155;
			
			// aapt resource value: 0x7f05002e
			public const int inserirFantaisa = 2131034158;
			
			// aapt resource value: 0x7f050030
			public const int inserirFiccao = 2131034160;
			
			// aapt resource value: 0x7f05002f
			public const int inserirGuia = 2131034159;
			
			// aapt resource value: 0x7f05005e
			public const int inserirLivro = 2131034206;
			
			// aapt resource value: 0x7f050033
			public const int inserirNomeLivro = 2131034163;
			
			// aapt resource value: 0x7f050036
			public const int inserirQuantidadePaginasLivro = 2131034166;
			
			// aapt resource value: 0x7f05002a
			public const int inserirRomance = 2131034154;
			
			// aapt resource value: 0x7f05002d
			public const int inserirTerror = 2131034157;
			
			// aapt resource value: 0x7f050044
			public const int lendoAnoPublicacao = 2131034180;
			
			// aapt resource value: 0x7f050043
			public const int lendoAutor = 2131034179;
			
			// aapt resource value: 0x7f050046
			public const int lendoBarraSeparacao = 2131034182;
			
			// aapt resource value: 0x7f050049
			public const int lendoInicioDaLeitura = 2131034185;
			
			// aapt resource value: 0x7f050037
			public const int lendoLayout2 = 2131034167;
			
			// aapt resource value: 0x7f05004a
			public const int lendoListViewTab = 2131034186;
			
			// aapt resource value: 0x7f050042
			public const int lendoNomeLivro = 2131034178;
			
			// aapt resource value: 0x7f050045
			public const int lendoPaginaAtual = 2131034181;
			
			// aapt resource value: 0x7f050047
			public const int lendoPagonaTotal = 2131034183;
			
			// aapt resource value: 0x7f050040
			public const int lendoReadUpdateImage = 2131034176;
			
			// aapt resource value: 0x7f050048
			public const int lendoTag = 2131034184;
			
			// aapt resource value: 0x7f050056
			public const int lidoAutor = 2131034198;
			
			// aapt resource value: 0x7f05004d
			public const int lidoInfoAnoPublicacao = 2131034189;
			
			// aapt resource value: 0x7f05004c
			public const int lidoInfoAutor = 2131034188;
			
			// aapt resource value: 0x7f050053
			public const int lidoInfoComentario = 2131034195;
			
			// aapt resource value: 0x7f050050
			public const int lidoInfoInicioDaLeitura = 2131034192;
			
			// aapt resource value: 0x7f05004b
			public const int lidoInfoNomeLivro = 2131034187;
			
			// aapt resource value: 0x7f05004e
			public const int lidoInfoPagonaTotal = 2131034190;
			
			// aapt resource value: 0x7f050052
			public const int lidoInfoRank = 2131034194;
			
			// aapt resource value: 0x7f05004f
			public const int lidoInfoTag = 2131034191;
			
			// aapt resource value: 0x7f050051
			public const int lidoInfoTerminoLeitura = 2131034193;
			
			// aapt resource value: 0x7f050054
			public const int lidoLayoutList = 2131034196;
			
			// aapt resource value: 0x7f050055
			public const int lidoNomeLivro = 2131034197;
			
			// aapt resource value: 0x7f050057
			public const int lidoRank = 2131034199;
			
			// aapt resource value: 0x7f050058
			public const int lido_listView = 2131034200;
			
			// aapt resource value: 0x7f050007
			public const int linearLayout1 = 2131034119;
			
			// aapt resource value: 0x7f050011
			public const int linearLayout2 = 2131034129;
			
			// aapt resource value: 0x7f050059
			public const int listView1 = 2131034201;
			
			// aapt resource value: 0x7f05005a
			public const int livroAlterarInformacoes = 2131034202;
			
			// aapt resource value: 0x7f05005c
			public const int livroRemover = 2131034204;
			
			// aapt resource value: 0x7f05005b
			public const int livroVerCapitulos = 2131034203;
			
			// aapt resource value: 0x7f05003a
			public const int nomeLivro = 2131034170;
			
			// aapt resource value: 0x7f05005f
			public const int nomeQueroLerItem = 2131034207;
			
			// aapt resource value: 0x7f05003d
			public const int numeroPaginaAtual = 2131034173;
			
			// aapt resource value: 0x7f05003f
			public const int numeroPaginaTotal = 2131034175;
			
			// aapt resource value: 0x7f05003c
			public const int paginaText = 2131034172;
			
			// aapt resource value: 0x7f050060
			public const int quantidadePaginasQueroLerItem = 2131034208;
			
			// aapt resource value: 0x7f050061
			public const int tem_certeza = 2131034209;
			
			// aapt resource value: 0x7f050005
			public const int textView1 = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int adicionar_capitulo = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int atualizar_leitura = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int capitulo_informacao = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int capitulo_Item = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int capitulos_list = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int editar_livro = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int iniciar_leitura = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int inserir_livro = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int leitura_item2 = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int lendo_item = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int lendo_tab = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int lido_informacao = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int lido_item = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int lido_tab = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int list_tab = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int livro_opcoes = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Main = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int queroLer_item = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int sim_nao = 2130903058;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int lendo = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int lido = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int queroLer = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
